name: MT-Linter
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Brain install
        # Install project
        run: |
          make install
      - name: MT-Linter Run
        # Run Linter
        run: |
          make lint
